using System.Collections;
using System.Collections.Generic;
using UnityEngine;


/* ï¿½ï¿½ï¿½ï¿½
 * ï¿½Eï¿½Åï¿½ï¿½ï¿½disableï¿½É‚ï¿½ï¿½ï¿½instantiate, OnEnableï¿½Å“ï¿½ï¿½ï¿½ï¿½nï¿½ß‚ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
 * ï¿½EPlayerï¿½Æ‚Ì‚ï¿½ï¿½Æ‚ï¿½
 * ï¿½@ï¿½EisTargeting    // ï¿½^ï¿½[ï¿½Qï¿½bï¿½gï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ÉŒÄ‚Ñoï¿½ï¿½
 * ï¿½@ï¿½Evoid PositionChanged()    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Æ‚Ìï¿½ï¿½Wï¿½Ì“ï¿½ï¿½ï¿½Ö‚ï¿½ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉŒÄ‚Ñoï¿½ï¿½
 * */


public class Enemy : MonoBehaviour
{
    [SerializeField] protected GameObject m_target_mark;
    [SerializeField] protected GameObject m_question_mark;
    protected float question_mark_time = 2.0f;
    protected float attack_time = 1.0f;
    protected float dead_time = 2.0f;

    [SerializeField] private Vector2 m_spawnPosition = new Vector2(10, -1);

    protected Camera m_camera;
    public bool isTargeting = false;

    // ï¿½Æ‚è‚ ï¿½ï¿½ï¿½ï¿½private
    protected int hp = 1;
    protected float speed = 1.0f;
    //private float attack = 1.0f;

    protected Rigidbody2D m_rig;
    protected Animator m_animator;
    protected bool _isDead = false;
    protected bool _isAttacking = false;

    [SerializeField] private bool _tmp_isPositionChanged = false;
    public EnemySensor sensor;
    public GameObject attackJDG;
    public float attackBeforeDuration;

    private void OnEnable()
    {
        m_camera = GameObject.Find("Main Camera").GetComponent<Camera>();//Camera.current;
        m_rig = this.GetComponent<Rigidbody2D>();
        m_animator = this.GetComponent<Animator>();
        Spawn();
    }

    // Start is called before the first frame update
    public virtual void Start()
    {
        // do nothing
    }

    // Update is called once per frame
    void Update()
    {
        Move();
        Targeting();

        // ï¿½È‰ï¿½ï¿½fï¿½oï¿½bï¿½Oï¿½p
        if (_tmp_isPositionChanged)
        {
            PositionChanged();
            _tmp_isPositionChanged = false;
        }

        if(sensor.isAttackOther){
            AttackPlayer();
        }
    }

    // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ğ¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ìï¿½ï¿½ï¿½
    // OnEnable()ï¿½ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½
    protected virtual void Spawn()
    {
        // ï¿½Xï¿½|ï¿½[ï¿½ï¿½ï¿½ÌêŠï¿½ï¿½ï¿½wï¿½ï¿½
        //Vector2 spawnPosition = m_camera.ViewportToWorldPoint(new Vector2(1.0f, 0.5f));
        m_spawnPosition.y = m_rig.position.y;

        //m_rig.position = m_spawnPosition;
    }

    protected virtual void Move()
    {
        // ï¿½Ğ‚Æ‚Ü‚ï¿½ï¿½ï¿½ï¿½Wï¿½ğ’¼ÚXï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
        m_rig.position += new Vector2(-speed * Time.deltaTime, 0);
    }

    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÉƒAï¿½^ï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½
    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì”ï¿½_ï¿½ï¿½ï¿½Íƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½gï¿½ÅŠï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é‚½ï¿½ßAï¿½Aï¿½^ï¿½bï¿½Nï¿½Ìƒï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
    protected void AttackPlayer()
    {
        // ï¿½Uï¿½ï¿½ï¿½ÌƒAï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½s
        if (!_isDead && !_isAttacking)
        {
            StartCoroutine("Attack_anim");
            StartCoroutine(AttackRange(attackBeforeDuration));
        }
    }
    IEnumerator AttackRange(float before){
        yield return new WaitForSeconds(before);
        attackJDG.SetActive(true);
        yield return new WaitForSeconds(0.001f);
        attackJDG.SetActive(false);
    }

    // ï¿½ï¿½ÉUï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    protected void AttackCastle()
    {
        // ï¿½ï¿½ÉÕ“ï¿½
        // ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½[ï¿½oï¿½[ï¿½É‚ï¿½ï¿½ï¿½H
    }

    protected void Dead()
    {
        m_rig.constraints = RigidbodyConstraints2D.FreezePosition;
        //  ï¿½ï¿½ï¿½ñ‚¾‚Æ‚ï¿½ï¿½Ì“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½
        if (!_isDead)
        {
            m_animator.SetBool("Die", true);
            m_question_mark.SetActive(false);
            _isDead = true;
            this.GetComponent<Collider2D>().enabled = false;
        }
    }

    public void Destroy_enemy()
    {
        Destroy(this.gameObject);
    }

    IEnumerator SetQuestionMark()
    {
        m_question_mark.SetActive(true);
        float tmp_speed = this.speed;
        this.speed = 0.0f;
        m_animator.SetBool("Stand", true);
        yield return new WaitForSeconds(question_mark_time);
        this.speed = tmp_speed;
        m_question_mark.SetActive(false);
        m_animator.SetBool("Stand", false);
    }

    IEnumerator Attack_anim()
    {
        _isAttacking = true;
        m_animator.SetBool("Attack", true);
        float tmp_speed = this.speed;
        this.speed = 0.0f;
        yield return new WaitForSeconds(attack_time);
        m_animator.SetBool("Attack", false);
        this.speed = tmp_speed;
        _isAttacking = false;
    }

    

    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½Ìƒ_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½ï¿½ó‚¯‚ï¿½iPlayerï¿½ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½ï¿½j
    protected void TakeDamage(int ap)
    {
        this.hp -= ap;
        if (this.hp <= 0)
        {
            this.hp = 0;
            Dead();
        }
    }

    // ï¿½^ï¿½[ï¿½Qï¿½bï¿½gï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ÉŒÄ‚Î‚ï¿½ï¿½
    public void Targeting()
    {
        if (isTargeting && !m_target_mark.activeSelf)
        {
            m_target_mark.SetActive(true);
        }
        else if (!isTargeting && m_target_mark.activeSelf)
        {
            m_target_mark.SetActive(false);
        }
    }

    public virtual void PositionChanged()
    {
        // ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚Í‚Ä‚Èƒ}ï¿½[ï¿½N
        StartCoroutine("SetQuestionMark");
    }



    // ï¿½Õ“Ë‘ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½ï¿½Tagï¿½ï¿½
    // Player or Castle
    public virtual void OnTriggerEnter2D(Collider2D collision)
    {

        GameObject opponent = collision.gameObject;    // ï¿½Õ“Ë‘ï¿½ï¿½ï¿½ï¿½ï¿½æ“¾
        Collider2D other = opponent.GetComponent<Collider2D>();

        if (other.CompareTag("Attack"))
        {
            TakeDamage(1);
        }
    }
}